### ISSUE TITLE
DB設計、構築

### ISSUE THREAD

**Issue by matopenKW** [matopenKW/waseda_covit19_docs_backend#8]
下記のDBを設計する
・Users
・活動内容記録表
・経路マスタ

**Comment by oshikun** [comment]
活動内容記録表のカラムを考えてから意見を頂けますか。
◆活動内容記録表テーブル
・ユーザーID
・役割（レギュラーor新練or卒演）
・内容
・会場

**Comment by matopenKW** [comment]
◆活動内容記録表テーブル
・ユーザーID　PK
・日付　PK
・開始時刻
・終了時刻
・練習区分
・練習内容
・会場ID
・経路ID
・接触者人数１
・接触概要１
・接触人数２
・接触概要２

でどうでしょうか。

SQLファイルを作ったら、local/db配下に置いてもらえると助かります。

**Comment by oshikun** [comment]
sqlファイルを作成したので確認をお願いします。

**Comment by matopenKW** [comment]
ごめんなさい。
コミットするときは 「#[issueNo]　コメント」って感じでやってもらえるとIssueに反映されるので助かります。

また、確認する場合はPR投げてくれても構いません。

**Comment by matopenKW** [comment]
活動内容記録表テーブルの経路は履歴として持つ必要があるため
経路IDではなく、経路（往路）、経路（復路）として文字型で持つ様に修正お願いします。

**Comment by oshikun** [comment]
@matopenKW 
DBとsqlを修正したので確認をお願いします。

**Comment by matopenKW** [comment]
migrateディレクトリを作成し、go-migrateで管理できる様に修正したため、本issueは削除
